export const PERSON_BIOGRAPHY_REQUESTED = 'PERSON_BIOGRAPHY_REQUESTED';
export const PERSON_BIOGRAPHY_LOADED = 'PERSON_BIOGRAPHY_LOADED';
export const PERSON_BIOGRAPHY_ERROR = 'PERSON_BIOGRAPHY_ERROR';

export const PERSON_SOCIAL_LINK_REQUESTED = 'PERSON_SOCIAL_LINK_REQUESTED';
export const PERSON_SOCIAL_LINK_LOADED = 'PERSON_SOCIAL_LINK_LOADED';
export const PERSON_SOCIAL_LINK_ERROR = 'PERSON_SOCIAL_LINK_ERROR';