export const POPULAR_MOVIES_REQUESTED = 'POPULAR_MOVIES_REQUESTED';
export const POPULAR_MOVIES_LOADED = 'POPULAR_MOVIES_LOADED';
export const POPULAR_MOVIES_ERROR = 'POPULAR_MOVIES_ERROR';
export const POPULAR_MOVIES_MORE_REQUESTED = 'POPULAR_MOVIES_MORE_REQUESTED';
export const POPULAR_MOVIES_MORE_LOADED = 'POPULAR_MOVIES_MORE_LOADED';
export const POPULAR_MOVIES_MORE_ERROR = 'POPULAR_MOVIES_MORE_ERROR';
export const PLAYING_NOW_MOVIES_REQUESTED = 'PLAYING_NOW_MOVIES_REQUESTED';
export const PLAYING_NOW_MOVIES_LOADED = 'PLAYING_NOW_MOVIES_LOADED';
export const PLAYING_NOW_MOVIES_MORE_REQUESTED = 'PLAYING_NOW_MOVIES_MORE_REQUESTED';
export const PLAYING_NOW_MOVIES_MORE_LOADED = 'PLAYING_NOW_MOVIES_MORE_LOADED';
export const UPCOMING_MOVIES_REQUESTED = 'UPCOMING_MOVIES_REQUESTED';
export const UPCOMING_MOVIES_LOADED = 'UPCOMING_MOVIES_LOADED';
export const UPCOMING_MOVIES_MORE_REQUESTED = 'UPCOMING_MOVIES_MORE_REQUESTED';
export const UPCOMING_MOVIES_MORE_LOADED = 'UPCOMING_MOVIES_MORE_LOADED';
export const TOP_RATED_MOVIES_REQUESTED = 'TOP_RATED_MOVIES_REQUESTED';
export const TOP_RATED_MOVIES_LOADED = 'TOP_RATED_MOVIES_LOADED';
export const TOP_RATED_MOVIES_MORE_REQUESTED = 'TOP_RATED_MOVIES_MORE_REQUESTED';
export const TOP_RATED_MOVIES_MORE_LOADED = 'TOP_RATED_MOVIES_MORE_LOADED';

export const POPULAR_TV_REQUESTED = 'POPULAR_TV_REQUESTED';
export const POPULAR_TV_LOADED = 'POPULAR_TV_LOADED';
export const POPULAR_TV_ERROR = 'POPULAR_TV_ERROR';
export const POPULAR_TV_MORE_REQUESTED = 'POPULAR_TV_MORE_REQUESTED';
export const POPULAR_TV_MORE_LOADED = 'POPULAR_TV_MORE_LOADED';
export const AIRING_TODAY_TV_REQUESTED = 'AIRING_TODAY_TV_REQUESTED';
export const AIRING_TODAY_TV_LOADED = 'AIRING_TODAY_TV_LOADED';
export const AIRING_TODAY_TV_MORE_REQUESTED = 'AIRING_TODAY_TV_MORE_REQUESTED';
export const AIRING_TODAY_TV_MORE_LOADED = 'AIRING_TODAY_TV_MORE_LOADED';
export const ON_THE_AIR_TV_REQUESTED = 'ON_THE_AIR_TV_REQUESTED';
export const ON_THE_AIR_TV_LOADED = 'ON_THE_AIR_TV_LOADED';
export const ON_THE_AIR_TV_MORE_REQUESTED = 'ON_THE_AIR_TV_MORE_REQUESTED';
export const ON_THE_AIR_TV_MORE_LOADED = 'ON_THE_AIR_TV_MORE_LOADED';
export const TOP_RATED_TV_REQUESTED = 'TOP_RATED_TV_REQUESTED';
export const TOP_RATED_TV_LOADED = 'TOP_RATED_TV_LOADED';
export const TOP_RATED_TV_MORE_REQUESTED = 'TOP_RATED_TV_MORE_REQUESTED';
export const TOP_RATED_TV_MORE_LOADED = 'TOP_RATED_TV_MORE_LOADED';

export const POPULAR_PERSON_REQUESTED = 'POPULAR_PERSON_REQUESTED';
export const POPULAR_PERSON_LOADED = 'POPULAR_PERSON_LOADED';
export const POPULAR_PERSON_ERROR = 'POPULAR_PERSON_ERROR';

export const MOVIE_DETAILS_REQUESTED = 'MOVIE_DETAILS_REQUESTED';
export const MOVIE_DETAILS_LOADED = 'MOVIE_DETAILS_LOADED';
export const MOVIE_DETAILS_ERROR = 'MOVIE_DETAILS_ERROR';

export const CAST_REQUESTED = 'CAST_REQUESTED';
export const CAST_LOADED = 'CAST_LOADED';

export const KEYWORDS_REQUESTED = 'KEYWORDS_REQUESTED';
export const KEYWORDS_LOADED = 'KEYWORDS_LOADED';

export const MODAL_WINDOW_TOGGLE = 'MODAL_WINDOW_TOGGLE';

export const VIDEO_LOADED = 'VIDEO_LOADED';

export const SOCIAL_LINK_LOADED = 'SOCIAL_LINK_LOADED';

export const COLLECTION_LOADED = 'COLLECTION_LOADED';