export const POPULAR_MOVIES_REQUESTED = 'POPULAR_MOVIES_REQUESTED';
export const POPULAR_MOVIES_LOADED = 'POPULAR_MOVIES_LOADED';
export const POPULAR_MOVIES_ERROR = 'POPULAR_MOVIES_ERROR';
export const POPULAR_MOVIES_MORE_REQUESTED = 'POPULAR_MOVIES_MORE_REQUESTED';
export const POPULAR_MOVIES_MORE_LOADED = 'POPULAR_MOVIES_MORE_LOADED';
export const POPULAR_MOVIES_MORE_ERROR = 'POPULAR_MOVIES_MORE_ERROR';