export const MOVIE_DETAILS_REQUESTED = 'MOVIE_DETAILS_REQUESTED';
export const MOVIE_DETAILS_LOADED = 'MOVIE_DETAILS_LOADED';
export const MOVIE_DETAILS_ERROR = 'MOVIE_DETAILS_ERROR';

export const CAST_REQUESTED = 'CAST_REQUESTED';
export const CAST_LOADED = 'CAST_LOADED';

export const KEYWORDS_REQUESTED = 'KEYWORDS_REQUESTED';
export const KEYWORDS_LOADED = 'KEYWORDS_LOADED';

export const MODAL_WINDOW_TOGGLE = 'MODAL_WINDOW_TOGGLE';

export const VIDEO_LOADED = 'VIDEO_LOADED';

export const SOCIAL_LINK_LOADED = 'SOCIAL_LINK_LOADED';

export const RECOMMENDATIONS_LOADED = 'RECOMMENDATIONS_LOADED';

export const RATING_REQUESTED = 'RATING_REQUESTED';
export const RATING_LOADED = 'RATING_LOADED';

export const MOVIE_DETAILS_COLLECTION_LOADED = 'MOVIE_DETAILS_COLLECTION_LOADED';