export const TV_SEARCH_REQUESTED = 'TV_SEARCH_REQUESTED';
export const TV_SEARCH_LOADED = 'TV_SEARCH_LOADED';
export const TV_SEARCH_ERROR = 'SEARCH_ERROR';

export const PERSON_SEARCH_REQUESTED = 'PERSON_SEARCH_REQUESTED';
export const PERSON_SEARCH_LOADED = 'PERSON_SEARCH_LOADED';
export const PERSON_SEARCH_ERROR = 'PERSON_SEARCH_ERROR';

export const MOVIE_SEARCH_REQUESTED = 'MOVIE_SEARCH_REQUESTED';
export const MOVIE_SEARCH_LOADED = 'MOVIE_SEARCH_LOADED';
export const MOVIE_SEARCH_ERROR = 'MOVIE_SEARCH_ERROR';

export const COMPANY_SEARCH_REQUESTED = 'COMPANY_SEARCH_REQUESTED';
export const COMPANY_SEARCH_LOADED = 'COMPANY_SEARCH_LOADED';
export const COMPANY_SEARCH_ERROR = 'COMPANY_SEARCH_ERROR';

export const KEYWORD_SEARCH_REQUESTED = 'KEYWORD_SEARCH_REQUESTED';
export const KEYWORD_SEARCH_LOADED = 'KEYWORD_SEARCH_LOADED';
export const KEYWORD_SEARCH_ERROR = 'KEYWORD_SEARCH_ERROR';

export const COLLECTION_SEARCH_REQUESTED = 'COLLECTION_SEARCH_REQUESTED';
export const COLLECTION_SEARCH_LOADED = 'COLLECTION_SEARCH_LOADED';
export const COLLECTION_SEARCH_ERROR = 'COLLECTION_SEARCH_ERROR';

export const IS_SEARCH = 'IS_SEARCH';