export const COLLECTION_REQUESTED = 'COLLECTION_REQUESTED';
export const COLLECTION_LOADED = 'COLLECTION_LOADED';
export const COLLECTION_ERROR = 'COLLECTION_ERROR';

export const GENRES_REQUESTED = 'GENRES_REQUESTED';
export const GENRES_LOADED = 'GENRES_LOADED';

export const COLLECTION_MOVIE_DETAILS_LOADED = 'COLLECTION_MOVIE_DETAILS_LOADED';

export const COLLECTION_CAST_LOADED = 'COLLECTION_CAST_LOADED';